/**
 * Standard Error Codes for the WhatsApp Auth System
 */
export enum ErrorCode {
  // Client & App Validation
  INVALID_CLIENT = 'INVALID_CLIENT',
  APPLICATION_NOT_FOUND = 'APPLICATION_NOT_FOUND',
  APPLICATION_DISABLED = 'APPLICATION_DISABLED',
  INVALID_CLIENT_SECRET = 'INVALID_CLIENT_SECRET',
  INVALID_REDIRECT_URI = 'INVALID_REDIRECT_URI',

  // Phone Validation
  INVALID_PHONE = 'INVALID_PHONE',

  // Authentication Flow
  AUTH_ATTEMPT_NOT_FOUND = 'AUTH_ATTEMPT_NOT_FOUND',
  AUTH_ATTEMPT_EXPIRED = 'AUTH_ATTEMPT_EXPIRED',
  AUTH_ATTEMPT_INVALID_STATE = 'AUTH_ATTEMPT_INVALID_STATE',
  CHALLENGE_INVALID = 'CHALLENGE_INVALID',
  CHALLENGE_ALREADY_USED = 'CHALLENGE_ALREADY_USED',
  CHALLENGE_MISMATCH = 'CHALLENGE_MISMATCH',
  PHONE_MISMATCH = 'PHONE_MISMATCH',
  TOO_MANY_FAILED_ATTEMPTS = 'TOO_MANY_FAILED_ATTEMPTS',

  // Token & Code Lifecycle
  LOGIN_TOKEN_NOT_FOUND = 'LOGIN_TOKEN_NOT_FOUND',
  LOGIN_TOKEN_EXPIRED = 'LOGIN_TOKEN_EXPIRED',
  LOGIN_TOKEN_ALREADY_USED = 'LOGIN_TOKEN_ALREADY_USED',
  AUTHORIZATION_CODE_NOT_FOUND = 'AUTHORIZATION_CODE_NOT_FOUND',
  AUTHORIZATION_CODE_EXPIRED = 'AUTHORIZATION_CODE_EXPIRED',
  AUTHORIZATION_CODE_ALREADY_USED = 'AUTHORIZATION_CODE_ALREADY_USED',
  INVALID_PKCE_VERIFIER = 'INVALID_PKCE_VERIFIER',
  INVALID_GRANT_TYPE = 'INVALID_GRANT_TYPE',

  // Sessions
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  SESSION_REVOKED = 'SESSION_REVOKED',

  // WhatsApp Worker & Infrastructure
  WHATSAPP_NOT_CONNECTED = 'WHATSAPP_NOT_CONNECTED',
  WORKER_UNAVAILABLE = 'WORKER_UNAVAILABLE',
  WORKER_UNAUTHORIZED = 'WORKER_UNAUTHORIZED',
  MESSAGE_DELIVERY_FAILED = 'MESSAGE_DELIVERY_FAILED',

  // Security & Rate Limits
  RATE_LIMITED = 'RATE_LIMITED',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
}

export interface ApiErrorResponse {
  success: false;
  error: {
    code: ErrorCode;
    message: string;
    details?: unknown;
    timestamp: string;
    requestId?: string;
  };
}

export class AppError extends Error {
  constructor(
    public readonly code: ErrorCode,
    message: string,
    public readonly statusCode: number = 400,
    public readonly details?: unknown
  ) {
    super(message);
    this.name = 'AppError';
    Object.setPrototypeOf(this, new.target.prototype);
  }
}
